Pagina
SaraMmejia/Proyecto-Make-it-Real pull request #14
Opened 2020-05-20 16:31 UTC by SaraMmejia

En esta Rama esta la pagina de ingreso y registro que nos hacía falta y es algo sumamente importante! 
Te envió la imagen para tener la idea de como va quedando.
Quedo atenta ante cualquier comentario, duda o inquietud  
![image](https://user-images.githubusercontent.com/57576199/82472104-3f392f80-9a8d-11ea-855f-cb8d3468bd8f.png)

2020-05-20 17:02 UTC, simonhoyos requested changes

2020-05-20 17:02 UTC, simonhoyos commented on cheaper/src/App.css
> +/* body {
Borrar los comentarios

2020-05-20 17:02 UTC, simonhoyos commented on cheaper/src/Components/NavBar.js
> +    <Router>
Acá no es necesario usar Router

2020-05-20 17:02 UTC, simonhoyos commented on cheaper/src/Components/Registro.css
> +
Borrar saltos de linea adicionales

2020-05-20 17:02 UTC, simonhoyos commented on cheaper/src/App.js
> +		|     <Route exact path="/" component={Registro} />
Acá hay caracteres raros, limpiar el código

2020-05-20 20:43 UTC, SaraMmejia commented on cheaper/src/App.css
> +/* body {
Simón con respecto a esto tengo una duda, o sea yo lo comente por que es un estilo que se está aplicando directamente en el App.css.
Lo recomendable sería aplicar ese estilo al componente pertinente no ?

2020-05-20 22:14 UTC, SaraMmejia commented
Quedaron listos los cambios, quedo atenta ante cualquier cambio y por favor también quedo pendiente con la funcionalidad de los botones, muchas gracias

2020-05-20 22:55 UTC, simonhoyos requested changes

2020-05-20 22:55 UTC, simonhoyos commented on cheaper/src/Components/formClient.css
> +body {
Por qué estos estilos acá y no en App.css? a mi me parece que son estilos de la aplicación o comunes para todos los componentes y no solo de este componente

2020-05-20 22:55 UTC, simonhoyos commented on cheaper/src/Components/Registro.js
> +	handleOnClick = (e) => {
Cambiar este toda la funcionalidad de los botones por links

2020-05-20 22:55 UTC, simonhoyos commented on cheaper/src/App.css
> -body {
Estos estilos deben ir en este archivo

2020-05-20 22:55 UTC, simonhoyos commented on cheaper/src/Components/NavBar.js
> +  BrowserRouter as Router,
Borrar el import de Router pues este no se esta usando

2020-05-20 22:55 UTC, simonhoyos commented on cheaper/src/Components/NavBar.js
> +      <Link to="/:IngresoSatisfactorio">Home de Ingreso</Link>
Borrar los dos puntos `:` de ingreso satisfactorio

2020-05-20 22:55 UTC, simonhoyos commented on cheaper/src/Components/Registro.js
> +import React from "react";
Es mejor nombrar los componentes en inglés

2020-05-21 04:52 UTC, SaraMmejia reviewed
Todas las correcciones quedaron aplicadas, cualquier cosa estaré atenta

2020-05-21 04:52 UTC, SaraMmejia commented on cheaper/src/Components/formClient.css
> +body {
Si tienes toda la razón, ya lo vuelvo a corregir

2020-05-21 15:21 UTC, simonhoyos approved these changes

2020-05-21 18:02 UTC, merged