Proveedores
SaraMmejia/Proyecto-Make-it-Real pull request #17
Opened 2020-05-22 02:50 UTC by SaraMmejia

Actualización de formulario de proveedores con sus respectivos estilos 
![image](https://user-images.githubusercontent.com/57576199/82626240-ebbe0300-9bac-11ea-8d97-805d06c402d9.png)

2020-05-22 18:42 UTC, simonhoyos requested changes

2020-05-22 18:42 UTC, simonhoyos commented on cheaper/src/App.js
> +          <Route exact path="/Login" component={Login} />
Login quedo duplicado

2020-05-22 18:42 UTC, simonhoyos commented on cheaper/src/Components/Registry.js
> +							<Link to="/Login" className ="Boton-IniciarSesion" >Iniciar Sesión</Link>
Login quedo triplicado

2020-05-22 18:58 UTC, SaraMmejia commented on cheaper/src/Components/Registry.js
> +							<Link to="/Login" className ="Boton-IniciarSesion" >Iniciar Sesión</Link>
Así lo tengo, haré pull nuevamente para ver si se corrige. 

![image](https://user-images.githubusercontent.com/57576199/82699692-b9ef7f80-9c32-11ea-867e-0fa9b790789a.png)

2020-05-22 18:58 UTC, SaraMmejia commented on cheaper/src/App.js
> +          <Route exact path="/Login" component={Login} />
Así lo tengo, haré pull nuevamente para ver si se corrige. 
![image](https://user-images.githubusercontent.com/57576199/82699612-96c4d000-9c32-11ea-9574-e8d550ad8be4.png)

2020-05-23 01:13 UTC, SaraMmejia commented
Quedo pendiente ante cualquier comentario!

2020-05-26 18:32 UTC, simonhoyos approved these changes

2020-05-26 18:59 UTC, closed without merging