Home
SaraMmejia/Proyecto-Make-it-Real pull request #20
Opened 2020-05-26 22:48 UTC by SaraMmejia

adjunto las actualizaciones del home, ya que en la rama anterior no se cargo el código por un pequeño error. 
![image](https://user-images.githubusercontent.com/57576199/82957590-f85da500-9f78-11ea-8c97-12fb4c11a4c9.png)

2020-05-26 23:38 UTC, simonhoyos requested changes

2020-05-26 23:38 UTC, simonhoyos commented on cheaper/debug.log
> +[0518/183816.421:ERROR:crash_report_database_win.cc(428)] unexpected header
Este archivo no debe existir en el PR, agregar al gitignore y removerlo completamente

2020-05-26 23:38 UTC, simonhoyos commented on cheaper/src/Components/NavBar.js
> +//       <Link to="/">Home</Link>
REmover comentarios

2020-05-26 23:38 UTC, simonhoyos commented on cheaper/src/components/newProviderForm.js
> +import "./newProviderForm.css";
ESta linea está duplicada

2020-05-27 02:51 UTC, SaraMmejia commented on cheaper/debug.log
> +[0518/183816.421:ERROR:crash_report_database_win.cc(428)] unexpected header
Simón este archivo lo ingrese al. .gitignore y puse los comandos del git que me compartiste anteriormente y no me da, igual lo haré nuevamente y ya cualquier cosa me avisas por fa

2020-05-27 03:30 UTC, SaraMmejia commented on cheaper/src/Components/NavBar.js
> +//       <Link to="/">Home</Link>
Borre todos las lineas comentadas, pero no puedo borrar el archivo por completo, me sale erro y no sé por que

2020-05-27 03:31 UTC, SaraMmejia commented on cheaper/src/components/newProviderForm.js
> +import "./newProviderForm.css";
Listo!! Quedó borrada está linea

2020-05-27 03:33 UTC, SaraMmejia commented
Quedo atenta ante los cambios o comentarios

2020-05-27 16:14 UTC, simonhoyos approved these changes

2020-05-27 21:21 UTC, merged