Product description
SaraMmejia/Proyecto-Make-it-Real pull request #25
Opened 2020-06-02 03:34 UTC by BrianOlaya

Saludos , se realiza vista de descripción de producto y de crear producto con menú lateral desplegable.

![product](https://user-images.githubusercontent.com/48833124/83476948-9957ce80-a457-11ea-91ad-df219aba7491.png)

![product1](https://user-images.githubusercontent.com/48833124/83476966-a8d71780-a457-11ea-8b1a-6bc72ffa61d7.png)

![product2](https://user-images.githubusercontent.com/48833124/83476983-af658f00-a457-11ea-842e-5c1442fe874c.png)

![create-product](https://user-images.githubusercontent.com/48833124/83476998-b7bdca00-a457-11ea-9f57-a7bd8990f17d.png)

![create-product1](https://user-images.githubusercontent.com/48833124/83477027-c73d1300-a457-11ea-8e70-e5a034bb270d.png)

2020-06-02 15:54 UTC, simonhoyos requested changes

2020-06-02 15:54 UTC, simonhoyos commented on cheaper/src/pages/NewClientFormCreate.js
> +				clientEmail={this.state.clientEmail}
Arreglar la identación

2020-06-02 15:54 UTC, simonhoyos commented on cheaper/src/pages/pgNewClientFormCreate.js
> +     <FormClient />
Arreglar la identación

2020-06-02 17:54 UTC, BrianOlaya commented on cheaper/src/pages/NewClientFormCreate.js
> +				clientEmail={this.state.clientEmail}
Identación corregida

2020-06-02 17:54 UTC, BrianOlaya commented on cheaper/src/pages/pgNewClientFormCreate.js
> +     <FormClient />
Identación corregida.

2020-06-02 21:32 UTC, simonhoyos approved these changes

2020-06-03 13:36 UTC, simonhoyos approved these changes

2020-06-03 14:36 UTC, merged