Formulario de cliente OK
SaraMmejia/Proyecto-Make-it-Real pull request #5
Opened 2020-05-15 22:26 UTC by BrianOlaya

Se realiza formulario de clientes, este es un diseño preliminar, pues aun faltarían definirse los colores y otros detalles. 

![image](https://user-images.githubusercontent.com/48833124/82100944-b73fd800-96d0-11ea-80be-44a119474f84.png)

2020-05-16 13:15 UTC, simonhoyos requested changes

2020-05-16 13:15 UTC, simonhoyos commented on cheaper/src/components/formClient.css
> +body {
Los estilos generales pueden ir en App.css o index.css

2020-05-16 13:15 UTC, simonhoyos commented on cheaper/src/components/formClient.css
> +   form {
Mejor usar un selector de clase, estos estilos se van a aplicar a todos los formularios y pueden haber errores

2020-05-16 13:15 UTC, simonhoyos commented on cheaper/package.json
> +  "description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
borra estas modificaciones

2020-05-16 13:15 UTC, simonhoyos commented on package.json
> +{
borra este archivo y package-lock.json que se crearon por fuera de la carpeta cheaper

2020-05-16 13:15 UTC, simonhoyos commented on cheaper/src/components/formClient.js
> +          // onChange={handleChange}
Sería bueno implementar esta funcionalidad de una vez y no dejar el código comentado

2020-05-16 13:15 UTC, simonhoyos commented on cheaper/src/components/formClient.css
> +  h1 {
Selectores por clase

2020-05-16 13:15 UTC, simonhoyos commented on cheaper/src/components/formClient.css
> +  img {
Lo mismo que arriba

2020-05-18 16:21 UTC, BrianOlaya commented on cheaper/src/components/formClient.css
> +body {
Se pasa los estilos a App.css

2020-05-18 16:22 UTC, BrianOlaya commented on cheaper/src/components/formClient.css
> +   form {
Se le agrega clase a esta etiqueta

2020-05-18 16:22 UTC, BrianOlaya commented on cheaper/package.json
> +  "description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
Se borran estas modificaciones

2020-05-18 16:23 UTC, BrianOlaya commented on cheaper/src/components/formClient.css
> +  h1 {
Se le agrega clases a esta etiquetas

2020-05-18 16:23 UTC, BrianOlaya commented on cheaper/src/components/formClient.css
> +  img {
Se agrega clases

2020-05-18 16:23 UTC, BrianOlaya commented on package.json
> +{
Se borra este archivo

2020-05-18 19:18 UTC, merged