Slider
SaraMmejia/Proyecto-Make-it-Real pull request #7
Opened 2020-05-16 02:34 UTC by BrianOlaya

Slider preliminar, el cual puede tener cambios en fuentes y colores. 

![image](https://user-images.githubusercontent.com/48833124/82108376-a2c10700-96f3-11ea-8b74-288af37b3de2.png)
![image](https://user-images.githubusercontent.com/48833124/82108380-a8b6e800-96f3-11ea-9088-7329f828463f.png)
![image](https://user-images.githubusercontent.com/48833124/82108390-b3717d00-96f3-11ea-8d0e-354b5a3a82c0.png)
![image](https://user-images.githubusercontent.com/48833124/82108384-aeacc900-96f3-11ea-9b04-c56c7409437b.png)

2020-05-16 14:00 UTC, simonhoyos requested changes

2020-05-18 17:33 UTC, BrianOlaya commented on cheaper/package.json
> +  "description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
Se borran estos cambios

2020-05-18 17:34 UTC, BrianOlaya commented on cheaper/src/components/slider.js
> +
se borran estos saltos de linea

2020-05-18 17:34 UTC, BrianOlaya commented on package.json
> +{
se borra estos archivos

2020-05-18 18:09 UTC, simonhoyos approved these changes

2020-05-18 18:40 UTC, merged

2020-05-18 19:24 UTC, simonhoyos commented
Recuerda borrar la rama después de hacer merge